version: '3'
services:
  postgresdb:
    image: "postgres:latest"
    environment: 
      POSTGRES_PASSWORD: 1234
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: bash -c "python mysite/manage.py runserver 0.0.0.0:8080"
